apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      restartPolicy: Always
      containers:
        - image: "harbor.k8s.elab.rs/banka-2/client:{{ .Values.backend.imageVer }}"
          imagePullPolicy: Always
          name: client
          env:
            - name: server.address
              value: 0.0.0.0
            - name: server.port
              value: "8083"
            - name: spring.datasource.url
              value: jdbc:mysql://relational:3306/backend?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: relational-creds
                  key: username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: relational-creds
                  key: password
            - name: spring.data.mongodb.uri
              value: mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ .Values.mongodb.service }}:27017/backend?authSource=admin
            - name: spring.cache.type
              value: redis
            - name: spring.data.redis.host
              value: redis
            - name: spring.data.redis.port
              value: "6379"
            - name: cache.host
              value: redis
            - name: cache.port
              value: "6379"
            - name: spring.cache.redis.time-to-live
              value: "900000"
            - name: service.users.host
              value: users:8080
            - name: service.users.client
              value: users:8081
            - name: service.users.otc
              value: users:8082
          ports:
            - containerPort: 8083
          command: ["java", "-jar", "app.jar"]

      initContainers:
        # Check that MySQL is running
        - name: assert-mysql
          image: alpine
          command: ["/bin/sh", "-c"]
          args: ["apk add --no-cache netcat-openbsd; until nc -z -v relational 3306; do echo Waiting for MySQL database; sleep 60; done"]

        # Check that MongoDB is running
        - name: assert-mongo
          image: mongo
          command: ["/bin/sh", "-c"]
          args: ["until mongosh \"mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ .Values.mongodb.service }}:27017/backend?authSource=admin\" --eval \"db.stats()\" > /dev/null 2>&1; do echo Waiting for MongoDB database; sleep 60; done"]

        # Check that MongoDB is running
        - name: assert-redis
          image: redis:7.0.11-alpine
          command: ["/bin/sh", "-c"]
          args: ["until echo PING | redis-cli -h redis -p 6379 > /dev/null 2>&1; do echo Waiting for Redis cache; sleep 60; done"]

        # Migrate schema to "{{ .Values.backend.imageVer }}" version
        - name: flyway
          image: "harbor.k8s.elab.rs/banka-2/flyway:{{ .Values.backend.imageVer }}"
          env:
            - name: url
              value: jdbc:mysql://relational:3306/backend?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
            - name: user
              valueFrom:
                secretKeyRef:
                  name: relational-creds
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: relational-creds
                  key: password
            - name: schemas
              value: backend
          command: ["/bin/sh", "-c"]
          args: ["until flyway migrate -url=$url -user=$user -password=$password; do echo Waiting for Flyway migration; sleep 60; done"]

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
  name: client
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: client
  type: ClusterIP