apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "harbor.k8s.elab.rs/banka-2/frontend:{{ .Values.frontend.imageVer }}"
          imagePullPolicy: Always
          ports:
            - name: frontend
              containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: frontend
