apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  retention: 7d
  scrapeInterval: 15s
  version: v2.42.0
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus: {{ .Values.namespace }}
  serviceMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      prometheus: {{ .Values.namespace }}
  podMonitorNamespaceSelector: {}
  resources:
    requests:
      cpu: 2
      memory: 16Gi
    limits:
      cpu: 2
      memory: 16Gi
  logLevel: info
  logFormat: logfmt
  securityContext:
    fsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 100Gi