apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users
  name: users
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      restartPolicy: Always
      containers:
        - image: "harbor.k8s.elab.rs/banka-2/users:{{ .Values.backend.imageVer }}"
          imagePullPolicy: Always
          name: users
          env:
            - name: server.address
              value: 0.0.0.0
            - name: server.port
              value: "8080"
            - name: spring.datasource.url
              value: jdbc:mysql://relational:3306/backend?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: relational-creds
                  key: username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: relational-creds
                  key: password
            - name: spring.data.mongodb.uri
              value: mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ .Values.mongodb.service }}:27017/backend?authSource=admin
            - name: spring.cache.type
              value: redis
            - name: spring.data.redis.host
              value: redis
            - name: spring.data.redis.port
              value: "6379"
            - name: cache.host
              value: redis
            - name: cache.port
              value: "6379"
            - name: spring.cache.redis.time-to-live
              value: "900000"
            - name: services.frontend.host
              value: TODO_add_value
          ports:
            - containerPort: 8080
          command: ["java", "-jar", "app.jar"]

      initContainers:
        # Check that MySQL is running
        - name: assert-mysql
          image: alpine
          command: ["/bin/sh", "-c"]
          args: ["apk add --no-cache netcat-openbsd; until nc -z -v relational 3306; do echo Waiting for MySQL database; sleep 60; done"]

        # Check that MongoDB is running
        - name: assert-mongo
          image: mongo
          command: ["/bin/sh", "-c"]
          args: ["until mongosh \"mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ .Values.mongodb.service }}:27017/backend?authSource=admin\" --eval \"db.stats()\" > /dev/null 2>&1; do echo Waiting for MongoDB database; sleep 60; done"]

        # Check that Redis is running
        - name: assert-redis
          image: redis:7.0.11-alpine
          command: ["/bin/sh", "-c"]
          args: ["until echo PING | redis-cli -h redis -p 6379 > /dev/null 2>&1; do echo Waiting for Redis cache; sleep 60; done"]

        # Wait for migration
        - name: assert-migrated
          image: mysql
          env:
            - name: host
              value: relational
            - name: port
              value: "3306"
            - name: database
              value: backend
            - name: user
              valueFrom:
                secretKeyRef:
                  name: relational-creds
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: relational-creds
                  key: password
          command: ["/bin/bash", "-c"]
          args: ["until mysql -sN -h$host -P$port -D$database -u$user -p$password --execute=\"select * from flyway_schema_history;\"; do echo Waiting on migration; sleep 30; done"]

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: users
  name: users
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: users
  type: ClusterIP